// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Product struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Scans       int32  `json:"scans"`
	ImageUrl    string `json:"image_url"`
}

type User struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	Email          string `json:"email"`
	PasswordHash   string `json:"password_hash"`
	FollowersCount int32  `json:"followers_count"`
	FollowingCount int32  `json:"following_count"`
}

type UserFollow struct {
	ID         int64     `json:"id"`
	FollowerID int64     `json:"follower_id"`
	FollowedID int64     `json:"followed_id"`
	FollowedAt time.Time `json:"followed_at"`
}

type UserScan struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	ProductID int64     `json:"product_id"`
	ScannedAt time.Time `json:"scanned_at"`
}
