// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash) 
VALUES ($1, $2, $3) 
RETURNING id, username, email, followers_count, following_count
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	Email          string `json:"email"`
	FollowersCount int32  `json:"followers_count"`
	FollowingCount int32  `json:"following_count"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FollowersCount,
		&i.FollowingCount,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, username, email, password_hash, followers_count, following_count FROM users
where (email = $1 or username = $1) and password_hash = $2
`

type GetUserByLoginParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserByLogin(ctx context.Context, arg GetUserByLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FollowersCount,
		&i.FollowingCount,
	)
	return i, err
}
